version = 0.1

[default.global.parameters]
stack_name = "firstaidflow"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
